In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from sklearn.neighbors import KNeighborsClassifier


df = pd.read_csv('cleaned_data_final.csv')

#Train test Split
from sklearn.model_selection import train_test_split

X1 = df[['step', 'amount', 'oldbalanceOrg','newbalanceOrig','oldbalanceDest','newbalanceDest', 'type', 'nameOrigDest']]
y1 = df['isFraud']

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.33, random_state=42)

## Original dataset

In [2]:
#original
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X1_train,y1_train)
pred = knn.predict(X1_test)

from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(y1_test,pred))
print(confusion_matrix(y1_test,pred))
print(classification_report(y1_test,pred))

AUC = roc_auc_score(y1_test, pred)
print('AUC:', AUC)

/Users/aakritinag/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Accuracy: 0.9994689616414086
[[2096816     173]
 [    942    1729]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   2096989
           1       0.91      0.65      0.76      2671

    accuracy                           1.00   2099660
   macro avg       0.95      0.82      0.88   2099660
weighted avg       1.00      1.00      1.00   2099660

AUC: 0.8236203003609915


## Oversampling

In [3]:
#Oversampling
rus=RandomOverSampler(random_state=42)

x_rus, y_rus=rus.fit_resample(X1_train,y1_train)

knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(x_rus,y_rus)
pred = knn.predict(X1_test)

print("Accuracy:",metrics.accuracy_score(y1_test,pred))
print(confusion_matrix(y1_test,pred))
print(classification_report(y1_test,pred))

AUC = roc_auc_score(y1_test, pred)
print('AUC:', AUC)

/Users/aakritinag/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Accuracy: 0.9992922663669356
[[2096223     766]
 [    720    1951]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   2096989
           1       0.72      0.73      0.72      2671

    accuracy                           1.00   2099660
   macro avg       0.86      0.87      0.86   2099660
weighted avg       1.00      1.00      1.00   2099660

AUC: 0.865036376266566


## Undersampling

In [4]:
#Undersampling
rus=RandomUnderSampler(random_state=42)

x_rus, y_rus=rus.fit_resample(X1_train,y1_train)

knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(x_rus,y_rus)
pred = knn.predict(X1_test)

print("Accuracy:",metrics.accuracy_score(y1_test,pred))
print(confusion_matrix(y1_test,pred))
print(classification_report(y1_test,pred))

AUC = roc_auc_score(y1_test, pred)
print('AUC:', AUC)

/Users/aakritinag/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Accuracy: 0.9702504214968137
[[2034690   62299]
 [    165    2506]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.98   2096989
           1       0.04      0.94      0.07      2671

    accuracy                           0.97   2099660
   macro avg       0.52      0.95      0.53   2099660
weighted avg       1.00      0.97      0.98   2099660

AUC: 0.9542582982665796
