In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score,classification_report,roc_auc_score,precision_score,recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
#delete
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')
import imblearn
from collections import Counter

In [2]:
df = pd.read_csv("cleaned_data_final.csv")

In [3]:
from sklearn.model_selection import train_test_split

X=df.drop(['isFraud'],axis=1)  # Features
y=df['isFraud']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42) # 67% training and 33% test

In [4]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=10, oob_score = True, random_state=42)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

In [5]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9997051903641542


In [6]:
from sklearn.metrics import confusion_matrix

In [7]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   2096989
           1       0.98      0.79      0.87      2671

    accuracy                           1.00   2099660
   macro avg       0.99      0.89      0.94   2099660
weighted avg       1.00      1.00      1.00   2099660

[[2096942      47]
 [    572    2099]]


In [8]:
# compute ROC AUC https://www.kaggle.com/code/prashant111/naive-bayes-classifier-in-python#12.-Model-training-

from sklearn.metrics import roc_auc_score

ROC_AUC = roc_auc_score(y_test, y_pred)

print('ROC AUC : {:.4f}'.format(ROC_AUC))

#ROC AUC is a single number summary of classifier performance. The higher the value, the better the classifier.

ROC AUC : 0.8929


# Undersampling dataset

In [9]:
# import library
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=42)# fit predictor and target variable
x_rus, y_rus = rus.fit_resample(X_train, y_train)

print('original dataset shape:', Counter(y_train))
print('Resample dataset shape', Counter(y_rus))

original dataset shape: Counter({0: 4257418, 1: 5526})
Resample dataset shape Counter({0: 5526, 1: 5526})


In [10]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=10, oob_score = True, random_state=42)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_rus,y_rus)
y_pred=clf.predict(X_test)

In [11]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9879613842241125


In [12]:
from sklearn.metrics import confusion_matrix

In [13]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99   2096989
           1       0.09      0.99      0.17      2671

    accuracy                           0.99   2099660
   macro avg       0.55      0.99      0.58   2099660
weighted avg       1.00      0.99      0.99   2099660

[[2071732   25257]
 [     20    2651]]


In [14]:
# compute ROC AUC https://www.kaggle.com/code/prashant111/naive-bayes-classifier-in-python#12.-Model-training-

from sklearn.metrics import roc_auc_score

ROC_AUC = roc_auc_score(y_test, y_pred)

print('ROC AUC : {:.4f}'.format(ROC_AUC))

#ROC AUC is a single number summary of classifier performance. The higher the value, the better the classifier.

ROC AUC : 0.9902


# Oversampling Dataset

In [15]:
# import library
from imblearn.over_sampling import RandomOverSampler
rus = RandomOverSampler(random_state=42)
x_rus, y_rus = rus.fit_resample(X_train, y_train)

print('original dataset shape:', Counter(y_train))
print('Resample dataset shape', Counter(y_rus))

original dataset shape: Counter({0: 4257418, 1: 5526})
Resample dataset shape Counter({0: 4257418, 1: 4257418})


In [16]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=10, oob_score = True, random_state=42)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_rus,y_rus)
y_pred=clf.predict(X_test)

In [17]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9997094767724298


In [18]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   2096989
           1       0.96      0.80      0.88      2671

    accuracy                           1.00   2099660
   macro avg       0.98      0.90      0.94   2099660
weighted avg       1.00      1.00      1.00   2099660

[[2096911      78]
 [    532    2139]]


In [19]:
# compute ROC AUC https://www.kaggle.com/code/prashant111/naive-bayes-classifier-in-python#12.-Model-training-

from sklearn.metrics import roc_auc_score

ROC_AUC = roc_auc_score(y_test, y_pred)

print('ROC AUC : {:.4f}'.format(ROC_AUC))

#ROC AUC is a single number summary of classifier performance. The higher the value, the better the classifier.

ROC AUC : 0.9004
