In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import average_precision_score
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score, roc_curve, auc, precision_score,mean_squared_error

In [2]:
data= pd.read_csv('cleaned_data_final.csv')
data.head()

step  type    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1     0   9839.64       170136.0       160296.36             0.0   
1     1     0   1864.28        21249.0        19384.72             0.0   
2     1     1    181.00          181.0            0.00             0.0   
3     1     2    181.00          181.0            0.00         21182.0   
4     1     0  11668.14        41554.0        29885.86             0.0   

   newbalanceDest  isFraud  nameOrigDest  
0             0.0        0             0  
1             0.0        0             0  
2             0.0        1             1  
3             0.0        1             1  
4             0.0        0             0

In [3]:
X = data.drop("isFraud",1)
y = data.isFraud

/var/folders/m4/yx3n91cs37nf91mrrvjx9s2r0000gn/T/ipykernel_29882/1851905219.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = data.drop("isFraud",1)


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [5]:
import xgboost as xgb

In [6]:
xgb_model = xgb.XGBClassifier(objective="binary:logistic", random_state=42)
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=42, ...)

In [7]:
predict = xgb_model.predict(X_test)

In [8]:
print(confusion_matrix(y_test,predict))

[[2096931      58]
 [    345    2326]]


In [9]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   2096989
           1       0.98      0.87      0.92      2671

    accuracy                           1.00   2099660
   macro avg       0.99      0.94      0.96   2099660
weighted avg       1.00      1.00      1.00   2099660



In [10]:
from sklearn.metrics import roc_auc_score

ROC_AUC = roc_auc_score(y_test, predict)

print('ROC AUC : {:.2f}'.format(ROC_AUC))

ROC AUC : 0.94


In [11]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test,predict))

Accuracy: 0.9998080641627692


In [12]:
#pip install -U scikit-learn

In [13]:
import imblearn
from collections import Counter

## Oversampling

In [14]:
from imblearn.over_sampling import RandomOverSampler
ros=RandomOverSampler(random_state=42)
x_ros, y_ros = ros.fit_resample(X_train, y_train)
print(Counter(y_train))
print(Counter(y_ros))

Counter({0: 4257418, 1: 5526})
Counter({0: 4257418, 1: 4257418})


In [15]:
xgb_model = xgb.XGBClassifier(objective="binary:logistic", random_state=42)
xgb_model.fit(x_ros, y_ros)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=42, ...)

In [16]:
predict = xgb_model.predict(X_test)

In [17]:
print(confusion_matrix(y_test,predict))

[[2094391    2598]
 [     30    2641]]


In [18]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   2096989
           1       0.50      0.99      0.67      2671

    accuracy                           1.00   2099660
   macro avg       0.75      0.99      0.83   2099660
weighted avg       1.00      1.00      1.00   2099660



In [19]:
from sklearn.metrics import roc_auc_score

ROC_AUC = roc_auc_score(y_test, predict)

print('ROC AUC : {:.2f}'.format(ROC_AUC))

ROC AUC : 0.99


In [20]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test,predict))

Accuracy: 0.9987483687835174


## Undersampling

In [21]:
from imblearn.under_sampling import RandomUnderSampler
rus=RandomUnderSampler(random_state=42)
x_rus, y_rus = rus.fit_resample(X_train, y_train)
print(Counter(y_train))
print(Counter(y_rus))

Counter({0: 4257418, 1: 5526})
Counter({0: 5526, 1: 5526})


In [22]:
xgb_model = xgb.XGBClassifier(objective="binary:logistic", random_state=42)
xgb_model.fit(x_rus, y_rus)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=42, ...)

In [23]:
predict = xgb_model.predict(X_test)

In [24]:
print(confusion_matrix(y_test,predict))

[[2079613   17376]
 [     12    2659]]


In [25]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00   2096989
           1       0.13      1.00      0.23      2671

    accuracy                           0.99   2099660
   macro avg       0.57      0.99      0.62   2099660
weighted avg       1.00      0.99      0.99   2099660



In [26]:
from sklearn.metrics import roc_auc_score

ROC_AUC = roc_auc_score(y_test, predict)

print('ROC AUC : {:.2f}'.format(ROC_AUC))

ROC AUC : 0.99


In [27]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test,predict))

Accuracy: 0.9917186592114914
